language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.5

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer create-project laravel/laravel --no-interaction --prefer-dist

before_script:
  - travis_retry composer update

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - behat
